# Generated by Django 2.0.1 on 2020-05-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
